config/routes.rb
Rails.application.routes.draw do
  
  # Static Pages
  root                 'static_pages#home'
  get     'about'   => 'static_pages#about'
  get     'help'    => 'static_pages#help'
  
  # Sessions
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  
  # Users
  resources :users
  get 'signup'              => 'users#new'
  get 'users/:id/personal'  => 'users#personal'
  get 'users/:id/contact'   => 'users#contact'
  
  # Events
  resources :events
  post 'events/:id/rsvp'    => 'events#rsvp'
  
  # Diary
  resources :diaries
end

app/models/diary.rb
class Diary < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  
  validates :user_id,   presence: true
  validates :event_id,  presence: true
  validates :entry,     presence: true
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  
  def index
    @diaries = Diary.where('user_id = ?', current_user.id)
    @events = current_user.events
  end
  
  def new
    @diary = Diary.new
    @event_id = params[:event]
  end
  
  def create
    @diary = Diary.new(diary_params)
    if @diary.save
      flash[:success] = "Diary Entry created"
      redirect_to diaries_url
    else
      flash.now[:danger] = "Coudln't save Diary Entry at this time"
      render 'new'
    end
  end
  
  def edit
    @diary = Diary.find(params[:id])
  end
  
  def update
    @diary = Diary.find(params[:id])
    
    if @diary.update_attributes(diary_params)
      flash[:success] = "Diary Entry updated"
      redirect_to diaries_url
    else
      flash.now[:danger] = "Coudln't update Diary Entry at this time"
      render 'update'
    end
  end
  
  private

    def diary_params
      params.require(:diary).permit(:user_id, :event_id, :entry)
    end
end

app/views/diaries/edit.html.erb
<div class="dropdown">
  <button class="button dropdown-toggle" type="button" data-toggle="dropdown">
    Prompts
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#" class="promptChoice">What I learned at this event was ...</a></li>
    <li><a href="#" class="promptChoice">After attending this event, I feel ...</a></li>
    <li><a href="#" class="promptChoice">The most important thing about this event was ...</a></li>
  </ul>
</div>
<div id="diary-edit">
  <%= form_for(@diary, html: { class: 'form-horizontal' }) do |f| %>
    <div class="editor centered">
      <table id="toolbar" class="centered">
        <tr>
          <td>
            <input type="button" class="toolbarButton boldButton" value="B">
          </td>
          <td>
            <input type="button" class="toolbarButton italicButton" value="I">
          </td>
          <td>
            <input type="button" class="toolbarButton underlineButton" value="U">
          </td>
          <td id="camIconTd"><img src="<%= asset_path('cam.png') %>" class="cameraButton"></td>
        </tr>
      </table>
      <div class="photoMenu">
        <div class="photo-options"><a href="">Take a Photo</a></div>
        <div class="photo-options"><a href="">Upload Photo</a></div>
        <div class="photo-options"><a href="">Use Check-In Photo</a></div>
      </div>
      <%= f.text_area :entry, class: 'form-control', id: 'contentArea', placeholder: "Enter text here ...", rows: '15' %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :event_id, :value => params[:event] %>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <%= f.submit "Update Entry", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/diaries/index.html.erb
<div id="diaryEvents">
  <% @events.each do |event| %>
    <div class="diaryEvent">
      <p class="title"><%= event.name %></p>
      <% diary = @diaries.find_by('event_id = ?', event.id) %>
      <% if diary.nil? %>
        <p class="text">
          <img src="<%= asset_path('empty.png') %>">
          Create an entry for this event...
        </p>
        <%= link_to new_diary_path + '?event=' + event.id.to_s, method: :get do %>
          <input type="submit" class="btn bnt-default" value="Create Entry">
        <% end %>
      <% else %>
        <p class="text">
          <img src="<%= asset_path('diary.jpg') %>">
          <%= diary.entry %>
        </p>
      <%= link_to edit_diary_path(diary) + '?event=' + event.id.to_s, method: :get do %>
          <input type="submit" class="btn bnt-default" value="Edit Entry">
        <% end %>
      <% end %>   
    </div>
  <% end %>
</div>

app/views/diaries/new.html.erb
<div class="dropdown">
  <button class="button dropdown-toggle" type="button" data-toggle="dropdown">
    Prompts
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><a href="#" class="promptChoice">What I learned at this event was ...</a></li>
    <li><a href="#" class="promptChoice">After attending this event, I feel ...</a></li>
    <li><a href="#" class="promptChoice">The most important thing about this event was ...</a></li>
  </ul>
</div>
<div id="diary-edit">
  <%= form_for(@diary, html: { class: 'form-horizontal' }) do |f| %>
    <div class="editor centered">
      <table id="toolbar" class="centered">
        <tr>
          <td>
            <input type="button" class="toolbarButton boldButton" value="B">
          </td>
          <td>
            <input type="button" class="toolbarButton italicButton" value="I">
          </td>
          <td>
            <input type="button" class="toolbarButton underlineButton" value="U">
          </td>
          <td id="camIconTd"><img src="<%= asset_path('cam.png') %>" class="cameraButton"></td>
        </tr>
      </table>
      <div class="photoMenu">
        <div class="photo-options"><a href="">Take a Photo</a></div>
        <div class="photo-options"><a href="">Upload Photo</a></div>
        <div class="photo-options"><a href="">Use Check-In Photo</a></div>
      </div>
      <%= f.text_area :entry, class: 'form-control', id: 'contentArea', placeholder: "Enter text here ...", rows: '15' %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.hidden_field :event_id, :value => params[:event] %>
    </div>
    <div class="form-group">
      <div class="col-sm-12">
        <%= f.submit "Save Entry", class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>