config/routes.rb
Rails.application.routes.draw do
  
  # Static Pages
  root                 'static_pages#home'
  get     'about'   => 'static_pages#about'
  get     'help'    => 'static_pages#help'
  
  # Sessions
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  
  # Users
  resources :users
  get 'signup'              => 'users#new'
  get 'users/:id/personal'  => 'users#personal'
  get 'users/:id/contact'   => 'users#contact'
  
  # Events
  resources :events
  post 'events/:id/rsvp'    => 'events#rsvp'
  
  # Diary
  resources :diaries
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category
  has_many   :diaries
  has_and_belongs_to_many :users
end

app/controllers/events_controller.rb
require 'date'

class EventsController < ApplicationController
  def index
    @category = Category.find_by(:id => params[:category])
    @past = params[:past] == 'true'
    
    # Not filtering by category
    if @category.blank?
      if @past
        @events = Event.where('date < ?', Date.today)
      else
        @events = Event.where('date >= ?', Date.today)
      end
    # Filtering by Category
    else
      @events = Event.where(category_id: @category.id).where('date >= ?', Date.today)
    end
  end

  def show
    @event = Event.find(params[:id])
    @past = @event.date < Date.today
    @rsvp = current_user.events.exists?(@event)
  end
  
  def rsvp
    @event = Event.find(params[:id])
    @rsvp = current_user.events.exists?(@event)
    
    # If the user has already RSVP'ed to the event, we delete it
    if @rsvp
      flash[:warning] = 'You are no longer going to "' + @event.name + '"'
      current_user.events.delete(@event)
      
    # If the user hasn't RSVP'ed to the event, we add it  
    else
      flash[:success] = 'You are now going to "' + @event.name + '"'
      current_user.events << @event
    end
    
    redirect_to @event
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<% provide(:title, 'Events') %>
<div class="row">
  <div id="filterDropdown" class="dropdown">
    <button id="filterButton" class="button dropdown-toggle" type="button" data-toggle="dropdown">
      Filter: 
      <span id="filterType">
        <% if @category %>
          <%= @category.name %>
        <% else %>
          None
        <% end %>
      </span>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="#" id="none" class="filterChoice">None</a></li>
      <% Category.all.each do |category| %>
        <li><a href="#" id="<%= category.id %>" class="filterChoice"><%= category.name %></a></li>
      <% end %>
    </ul>
  </div>
  <div class="tabs">
    <%= link_to events_path, method: :get do %>
      <% if @past %>
        <div class="right-tab-unselected">Upcoming</div>
      <% else %>
        <div class="right-tab-selected">Upcoming</div>
      <% end %>
    <% end %>
    <%= link_to events_path(past: true), method: :get do %>
      <% if @past %>
        <div class="left-tab-selected">Past</div>
      <% else %>
        <div class="left-tab-unselected">Past</div>
      <% end %>
    <% end %>
  </div>
  <div id="events" class="container">
    <% @events.each do |event| %>
      <div class="row event <%= event.category.id %>">
        <span class="title"><%= link_to event.name, event_path(event) %></span>
        <span class="date"><%= event.date.strftime('%m/%d - %I:%M %p') %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.name.html_safe) %>

<div class="row">
  <div id="event-tab">
    <%= @event.name %>
  </div>
  <div id="event-date">
    <%= @event.date.strftime('%A, %B %d - %I:%M %p') %>
  </div>
  <div id="event-points">
    (<%= @event.points %> pts)
  </div>
  <div id="event-category">
    <%=link_to @event.category.name, events_path(category: @event.category.id) %>
  </div>
  <div id="event-container">
    <p id="event-info"><%= @event.description %></p>
    <div id="event-location">
      <h3>Location</h3>
      <p><em><%= @event.location %></em></p>
      <iframe
        width="100%"
        height="300"
        frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAI-5poQz6PbunOcFob_YEFkGInXhaCfkg
             &q= <%= @event.location %>" allowfullscreen>
      </iframe>
    </div>
    <h3>
      <% if @past %>
        Who went?
      <% else %>
        Who is going?
      <% end %>
    </h3>
    <div id="attendees" class="row">
      <% @event.users.each do |user| %>
        <%= link_to user_path(user) do %>
          <div class="attendee">
            <div class="placeholder">
              <% if asset_exists?(user.email + ".jpg") %>
                <img src="<%= asset_path(user.email + ".jpg") %>" width="45px" height="45px">
              <% end %>
            </div>
              <%= user.name %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div id="more">
      <a href=''>more</a>
    </div>
    
    <% if @rsvp %>
      <%= button_to "I'm going", event_path(@event) + '/rsvp', class: "btn btn-default btn-rsvp btn-going" , method: :post %>
    <% else %>
      <%= button_to "Are you going?", event_path(@event) + '/rsvp', class: "btn btn-default btn-rsvp btn-not-going" , method: :post %>
    <% end %>
    
    <h3>Posts</h3>
    <textarea class="post user-post" rows="4" placeholder="Create a post..."></textarea>
    <div class="user-post-links">
      <a href="#">Post</a>
    </div>

    <div class="post">
      Maria F.
      <p>Can't miss it!</p>
      <div class="post-links">
        <div class="reply" id="reply1"><a>reply</a></div>
      </div>
      <div class="replyPanel" id="panel1" style="display:none;">
        <p>Valentina</p>
        <textarea rows="1"  placeholder="Write a reply..."></textarea>
        <div class="user-post-links">
            <a>Send</a>
        </div>
      </div>
    </div>
     <div class="user-post-links">
      <a href="#">Report</a>
    </div>

    <div class="post">
      Sarah A.
      <p>Looking for a carpool...</p>
      <div class="post-links">
        <div class="reply" id="reply2"><a>reply</a></div>
      </div>
      <div class="replyPanel" id="panel2" style="display:none;">
        <p>Valentina</p>
        <textarea rows="1"  placeholder="Write a reply..."></textarea>
        <div class="user-post-links">
            <a>Send</a>
        </div>
      </div>
    </div>
     <div class="user-post-links">
      <a href="#">Report</a>
    </div>
  </div>
</div>
</div>
</body>

</html>