config/routes.rb
Rails.application.routes.draw do
  
  # Static Pages
  root                 'static_pages#home'
  get     'about'   => 'static_pages#about'
  get     'help'    => 'static_pages#help'
  
  # Sessions
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'
  
  # Users
  resources :users
  get 'signup'              => 'users#new'
  get 'users/:id/personal'  => 'users#personal'
  get 'users/:id/contact'   => 'users#contact'
  
  # Events
  resources :events
  post 'events/:id/rsvp'    => 'events#rsvp'
  
  # Diary
  resources :diaries
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if params[:controller] == 'events' && params[:action] == 'show' %>
        <a class="navbar-brand" href="<%= events_path %>"><i class="fa fa-chevron-left"></i></a>
      <% elsif params[:controller] == 'diaries' && params[:action] == 'new' %>
        <a class="navbar-brand" href="<%= diaries_path %>"><i class="fa fa-chevron-left"></i></a>
      <% elsif params[:controller] == 'diaries' && params[:action] == 'edit' %>
        <a class="navbar-brand" href="<%= diaries_path %>"><i class="fa fa-chevron-left"></i></a>
      <% else %>
        <%= link_to "UCB", root_path, class: "navbar-brand", id: "logo" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'events' %>"><%= link_to 'Events', events_path, method: :get %></li>
        <li class=""><a href="#">Check In</a></li>
        <li class="<%= 'active' if params[:controller] == 'diaries' %>"><%= link_to 'My Diary', diaries_path, method: :get %></li>
        <li class="<%= 'active' if current_page?(help_path) %>"><%= link_to 'Help', help_path %></li>
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to 'About Us', about_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <% if logged_in? %>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user fa-fw"></i>&nbsp; 
            <%= @current_user.name.split.first %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#"><strong>575 Points</strong></a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'View Profile', current_user %></li>
            <li><%= link_to 'Edit Profile', '/users/' + current_user.id.to_s + '/personal' %></li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to 'Sign out', logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css' rel='stylesheet' type='text/css'/>
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,400italic,300italic,600,600italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>